# Generated by Django 2.2.6 on 2019-10-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='型号名称')),
                ('series', models.SmallIntegerField(choices=[(0, 'ct680'), (1, '5000'), (2, '600')], verbose_name='系列')),
                ('desc', models.CharField(max_length=256, verbose_name='型号描述')),
                ('bottom_seal', models.BooleanField(verbose_name='有无底胶')),
                ('top_seal', models.BooleanField(verbose_name='有无顶胶')),
                ('top_mechanism', models.BooleanField(verbose_name='有无顶撑')),
                ('top_clearance', models.IntegerField(verbose_name='顶部虚位')),
                ('bottom_mechanism', models.BooleanField(verbose_name='有无底撑')),
                ('bottom_clearance', models.IntegerField(verbose_name='底部虚位')),
                ('basic_material', models.SmallIntegerField(choices=[(0, '石膏板'), (1, '木夹板'), (2, '无')], verbose_name='基本板材')),
                ('steel_plate', models.SmallIntegerField(choices=[(0, '内'), (1, '外'), (2, '无')], verbose_name='钢板')),
                ('rockwool', models.BooleanField(verbose_name='有无岩棉')),
            ],
            options={
                'verbose_name_plural': '屏风模型',
                'db_table': 'df_models',
                'verbose_name': '屏风模型',
            },
        ),
    ]
