# Generated by Django 2.2.6 on 2019-11-27 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartPicModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='组件名称标识')),
                ('paneltype', models.SmallIntegerField(choices=[(0, '普通屏风'), (1, '玻璃屏风'), (2, '收板间门')], verbose_name='屏风种类')),
                ('panelpart', models.SmallIntegerField(choices=[(0, '左边'), (1, '中间'), (2, '轮子'), (3, '右边'), (4, '文字')], verbose_name='组件位置')),
                ('svgcode', models.CharField(max_length=512, verbose_name='图元组件代码')),
                ('is_activate', models.BooleanField(default=False, verbose_name='激活标记')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '图元组件模型',
                'db_table': 'df_svgparts',
                'verbose_name': '图元组件模型',
            },
        ),
        migrations.CreateModel(
            name='PicsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='组件名称标识')),
                ('paneltype', models.SmallIntegerField(choices=[(0, '普通屏风'), (1, '玻璃屏风'), (2, '收板间门')], verbose_name='屏风种类')),
                ('wheeltype', models.SmallIntegerField(choices=[(0, '多向式'), (1, '单向式')], verbose_name='轮子分类')),
                ('pictype', models.SmallIntegerField(choices=[(0, 'BP'), (1, 'LCP'), (2, 'BSP'), (3, 'WJ'), (4, 'UIPD'), (5, 'LIPD'), (6, 'FP')], verbose_name='图元种类')),
                ('extra_length', models.SmallIntegerField(default=0, verbose_name='额外长度')),
                ('pin_mark', models.BooleanField(default=False, verbose_name='是否有地针')),
                ('is_activate', models.BooleanField(default=False, verbose_name='激活标记')),
                ('leftside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftside', to='standard.PartPicModels', verbose_name='左边组件图元')),
                ('middle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle', to='standard.PartPicModels', verbose_name='中间组件图元')),
                ('rightside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rightside', to='standard.PartPicModels', verbose_name='右边组件图元')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='standard.PartPicModels', verbose_name='文字组件图元')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel', to='standard.PartPicModels', verbose_name='轮子组件图元')),
            ],
            options={
                'verbose_name_plural': '图元模型',
                'db_table': 'df_pics',
                'verbose_name': '图元模型',
            },
        ),
        migrations.CreateModel(
            name='PanelModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=128, verbose_name='型号名称')),
                ('series', models.SmallIntegerField(choices=[(0, 'CT680'), (1, '5000'), (2, '600')], verbose_name='系列')),
                ('desc', models.CharField(max_length=256, verbose_name='型号描述')),
                ('bottom_option', models.SmallIntegerField(choices=[(0, '机动底撑 带 胶条'), (1, '机动底撑 不带 胶条'), (2, '胶条'), (3, '电动底撑 带 胶条'), (4, '电动底撑 不带 胶条')], default=0, verbose_name='底部选项')),
                ('bottom_clearance', models.SmallIntegerField(verbose_name='底部虚位')),
                ('top_option', models.SmallIntegerField(choices=[(0, '机动顶撑 带 胶条'), (1, '机动顶撑 不带 胶条'), (2, '胶条'), (3, '电动顶撑 带 胶条'), (4, '电动顶撑 不带 胶条')], default=0, verbose_name='顶部选项')),
                ('top_clearance', models.SmallIntegerField(verbose_name='顶部虚位')),
                ('basic_material', models.SmallIntegerField(choices=[(0, '石膏板'), (1, '木夹板'), (2, '无')], verbose_name='基本板材')),
                ('steel_plate', models.SmallIntegerField(choices=[(0, '内'), (1, '外'), (2, '无')], verbose_name='钢板')),
                ('rockwool', models.SmallIntegerField(choices=[(0, '50kg岩棉'), (1, '无岩棉')], verbose_name='有无岩棉')),
                ('wheel_type', models.SmallIntegerField(choices=[(0, '多向式'), (1, '单向式')], default=0, verbose_name='屏风类型')),
                ('is_activate', models.BooleanField(default=False, verbose_name='激活标记')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '屏风模型',
                'db_table': 'df_models',
                'verbose_name': '屏风模型',
            },
        ),
    ]
