# Generated by Django 2.2.6 on 2019-11-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelmodels',
            name='basic_material',
            field=models.SmallIntegerField(choices=[(0, '石膏板'), (1, '木夹板'), (2, '玻璃'), (3, '其他装饰面板材')], verbose_name='基本板材'),
        ),
    ]
