# Generated by Django 2.2.6 on 2019-10-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartPicModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='组件名称标识')),
                ('panelType', models.SmallIntegerField(choices=[(0, 'CommonPanels'), (1, 'GlassPanels'), (2, 'PocketDoor')], verbose_name='屏风种类')),
                ('pinPart', models.SmallIntegerField(choices=[(0, 'LeftSide'), (1, 'MiddleBody'), (3, 'Wheel'), (4, 'RightSide')], verbose_name='组件位置')),
                ('svgCode', models.CharField(max_length=256, verbose_name='图元组件代码')),
            ],
            options={
                'verbose_name_plural': '图元组件模型',
                'verbose_name': '图元组件模型',
                'db_table': 'df_svgparts',
            },
        ),
    ]
