# Generated by Django 2.2.6 on 2019-12-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_auto_20191127_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picsmodels',
            name='wheeltype',
        ),
        migrations.AddField(
            model_name='picsmodels',
            name='wheelquantity',
            field=models.SmallIntegerField(choices=[(0, '双轮'), (1, '单轮'), (3, '无轮')], default=0, verbose_name='轮子数量'),
        ),
    ]
