# Generated by Django 2.2.6 on 2019-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_auto_20191206_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelmodels',
            name='basic_material',
            field=models.SmallIntegerField(choices=[(0, 'Gypsum Board(石膏板)'), (1, 'Plywood Board(木夹板)'), (2, 'Tamper Glass(玻璃)'), (3, 'Others Decoration Board(其他装饰面板材)')], verbose_name='基本板材'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='bottom_option',
            field=models.SmallIntegerField(choices=[(0, 'Mechanical With Sweep Seal(机动底撑 带 胶条)'), (1, 'Mechanical Without Sweep Seal(机动底撑 不带 胶条)'), (2, 'Sweep Seal Only(只做胶条)'), (3, 'Ele. Mech. With Sweep Seal(电动底撑 带 胶条)'), (4, 'Ele. Mech. Without Sweep Seal(电动底撑 不带 胶条)')], default=0, verbose_name='底部选项'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='steel_plate',
            field=models.SmallIntegerField(choices=[(0, 'Serface(钢板面)'), (1, 'Inside(钢板底)'), (2, 'None(无钢板)')], verbose_name='钢板'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='top_option',
            field=models.SmallIntegerField(choices=[(0, 'Mechanical With Sweep Seal(机动顶撑 带 胶条)'), (1, 'Mechanical Without Sweep Seal(机动顶撑 不带 胶条)'), (2, 'Sweep Seal Only(只做胶条)'), (3, 'Ele. Mech. With Sweep Seal(电动顶撑 带 胶条)'), (4, 'Ele. Mech. Without Sweep Seal(电动顶撑 不带 胶条)')], default=0, verbose_name='顶部选项'),
        ),
    ]
