# Generated by Django 2.2.6 on 2019-10-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_auto_20191014_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpicmodels',
            name='panelPart',
            field=models.SmallIntegerField(choices=[(0, 'LeftSide'), (1, 'MiddleBody'), (2, 'Wheel'), (3, 'RightSide')], verbose_name='组件位置'),
        ),
    ]
