# Generated by Django 2.2.6 on 2019-10-14 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_auto_20191014_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partpicmodels',
            old_name='panelPart',
            new_name='panelpart',
        ),
        migrations.RenameField(
            model_name='partpicmodels',
            old_name='panelType',
            new_name='paneltype',
        ),
        migrations.RenameField(
            model_name='partpicmodels',
            old_name='svgCode',
            new_name='svgcode',
        ),
    ]
