# Generated by Django 2.2.6 on 2019-12-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0004_auto_20191210_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelmodels',
            name='bottom_option',
            field=models.SmallIntegerField(choices=[(0, 'Mechanical And Sweep Seal(机动底撑 带 胶条)'), (1, 'Mechanical Seal(机动底撑 不带 胶条)'), (2, 'Sweep Seal Only(只做胶条)'), (3, 'Ele. Mech. And Sweep Seal(电动底撑 带 胶条)'), (4, 'Ele. Mech. Seal(电动底撑 不带 胶条)')], default=0, verbose_name='底部选项'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='rockwool',
            field=models.SmallIntegerField(choices=[(0, '有岩棉'), (1, '无岩棉')], verbose_name='有无岩棉'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='top_option',
            field=models.SmallIntegerField(choices=[(0, 'Mechanical And Sweep Seal(机动顶撑 带 胶条)'), (1, 'Mechanical Seal(机动顶撑 不带 胶条)'), (2, 'Sweep Seal Only(只做胶条)'), (3, 'Ele. Mech. And Sweep Seal(电动顶撑 带 胶条)'), (4, 'Ele. Mech. Seal(电动顶撑 不带 胶条)')], default=0, verbose_name='顶部选项'),
        ),
    ]
