# Generated by Django 2.2.6 on 2019-10-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_auto_20191014_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpicmodels',
            name='svgcode',
            field=models.CharField(max_length=512, verbose_name='图元组件代码'),
        ),
    ]
