# Generated by Django 2.2.6 on 2020-01-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_auto_20191227_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picsmodels',
            name='wheelquantity',
            field=models.SmallIntegerField(choices=[(0, '双轮'), (1, '单轮'), (2, '无轮')], default=0, verbose_name='轮子数量'),
        ),
    ]
