# Generated by Django 2.2.6 on 2020-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_auto_20200116_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmodels',
            name='paneltype',
            field=models.SmallIntegerField(choices=[(0, '普通屏风'), (1, '玻璃屏风'), (2, '收板间门')], default=0, verbose_name='屏风种类'),
        ),
    ]
