# Generated by Django 2.2.6 on 2019-10-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_auto_20191015_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='组件名称标识')),
                ('paneltype', models.SmallIntegerField(choices=[(0, 'CommonPanels'), (1, 'GlassPanels'), (2, 'PocketDoor')], verbose_name='屏风种类')),
                ('wheeltype', models.SmallIntegerField(choices=[(0, 'DOULE'), (1, 'SINGLE')], verbose_name='轮子分类')),
                ('pictype', models.SmallIntegerField(choices=[(0, 'BP'), (1, 'LCP'), (2, 'BSP'), (3, 'WJ'), (4, 'UIPD'), (5, 'LIPD'), (6, 'FP')], verbose_name='图元种类')),
                ('extra_length', models.SmallIntegerField(default=0, verbose_name='额外长度')),
                ('leftside', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='leftside', to='standard.PartPicModels', verbose_name='左边组件图元')),
                ('middle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='middle', to='standard.PartPicModels', verbose_name='中间组件图元')),
                ('rightside', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rightside', to='standard.PartPicModels', verbose_name='右边组件图元')),
                ('wheel', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wheel', to='standard.PartPicModels', verbose_name='轮子组件图元')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
