# Generated by Django 2.2.6 on 2019-10-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0007_picsmodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picsmodels',
            options={'verbose_name': '图元模型', 'verbose_name_plural': '图元模型'},
        ),
        migrations.AlterModelTable(
            name='picsmodels',
            table='df_pics',
        ),
    ]
