# Generated by Django 2.2.6 on 2019-10-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_auto_20191016_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmodels',
            name='face_structure',
            field=models.SmallIntegerField(choices=[(0, '非600钢结构'), (1, '固面带收边'), (2, '易面带收边'), (3, '固面不带收边')], default=0, verbose_name='600钢结构'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='basic_material',
            field=models.SmallIntegerField(choices=[(0, '石膏板'), (1, '木夹板'), (3, '无')], verbose_name='基本板材'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='bottom_clearance',
            field=models.SmallIntegerField(verbose_name='底部虚位'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='name',
            field=models.CharField(max_length=128, verbose_name='型号名称'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='top_clearance',
            field=models.SmallIntegerField(verbose_name='顶部虚位'),
        ),
    ]
