# Generated by Django 2.2.6 on 2019-10-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0009_auto_20191016_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelmodels',
            name='face_structure',
        ),
    ]
