# Generated by Django 2.2.6 on 2019-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0010_remove_panelmodels_face_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelmodels',
            name='bottom_mechanism',
        ),
        migrations.RemoveField(
            model_name='panelmodels',
            name='bottom_seal',
        ),
        migrations.RemoveField(
            model_name='panelmodels',
            name='top_mechanism',
        ),
        migrations.RemoveField(
            model_name='panelmodels',
            name='top_seal',
        ),
        migrations.AddField(
            model_name='panelmodels',
            name='bottom_option',
            field=models.BooleanField(choices=[(0, '机动底撑 带 胶条'), (1, '机动底撑 不带 胶条'), (2, '胶条')], default=0, verbose_name='有无底胶'),
        ),
        migrations.AddField(
            model_name='panelmodels',
            name='top_option',
            field=models.BooleanField(choices=[(0, '机动顶撑 带 胶条'), (1, '机动顶撑 不带 胶条'), (2, '胶条')], default=0, verbose_name='有无顶胶'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='basic_material',
            field=models.SmallIntegerField(choices=[(0, '石膏板'), (1, '木夹板'), (2, '无')], verbose_name='基本板材'),
        ),
    ]
