# Generated by Django 2.2.6 on 2019-11-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0012_auto_20191114_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelmodels',
            name='bottom_option',
            field=models.BooleanField(choices=[(0, '机动底撑 带 胶条'), (1, '机动底撑 不带 胶条'), (2, '胶条')], default=0, verbose_name='底部选项'),
        ),
        migrations.AlterField(
            model_name='panelmodels',
            name='top_option',
            field=models.BooleanField(choices=[(0, '机动顶撑 带 胶条'), (1, '机动顶撑 不带 胶条'), (2, '胶条')], default=0, verbose_name='顶部选项'),
        ),
        migrations.AlterField(
            model_name='picsmodels',
            name='paneltype',
            field=models.SmallIntegerField(choices=[(0, '普通屏风'), (1, '玻璃屏风'), (2, '收板间门')], verbose_name='屏风种类'),
        ),
    ]
