# Generated by Django 2.2.6 on 2019-12-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app_permiss',
        ),
    ]
