# Generated by Django 2.2.4 on 2019-08-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_activate',
            field=models.BooleanField(default=False, verbose_name='电邮激活'),
        ),
    ]
