# Generated by Django 2.2.6 on 2019-10-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name': '权限表', 'verbose_name_plural': '权限表'},
        ),
        migrations.AlterModelTable(
            name='userpermission',
            table='df_userpermission',
        ),
    ]
