# Generated by Django 2.2.6 on 2019-11-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191011_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_permiass',
            field=models.CharField(default='', max_length=256, verbose_name='app权限'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_permiass',
            field=models.CharField(default='', max_length=256, verbose_name='区域权限'),
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
