# Generated by Django 2.2.6 on 2019-10-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('project_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='工程编号')),
                ('name', models.CharField(max_length=256, verbose_name='工程名称')),
                ('address', models.CharField(default='', max_length=256, verbose_name='工程地址')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
            ],
            options={
                'verbose_name_plural': '项目列表',
                'db_table': 'df_projects',
                'verbose_name': '项目列表',
            },
        ),
    ]
