# Generated by Django 2.2.6 on 2019-11-27 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('project_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='工程编号')),
                ('name', models.CharField(max_length=256, verbose_name='工程名称')),
                ('address', models.CharField(default='', max_length=256, verbose_name='工程地址')),
                ('projectlocation', models.SmallIntegerField(choices=[(0, 'HPF'), (1, 'HHKD'), (2, 'HGZ'), (3, 'HSH'), (4, 'HDL')], default=0, verbose_name='项目区域')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
                'db_table': 'df_projects',
            },
        ),
    ]
