# Generated by Django 2.2.6 on 2019-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191127_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='is_favorites',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
    ]
