# Generated by Django 2.2.6 on 2019-10-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projects_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectlocation',
            field=models.SmallIntegerField(choices=[(0, 'HPF'), (1, 'HHKD'), (2, 'HGZ'), (3, 'HSH'), (4, 'HDL')], default=0, verbose_name='项目区域'),
        ),
    ]
