# Generated by Django 2.2.4 on 2019-09-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190906_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='request_time',
            field=models.DateTimeField(verbose_name='出厂时间'),
        ),
    ]
