# Generated by Django 2.2.5 on 2019-09-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190906_1126'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='df_projects',
        ),
    ]
