# Generated by Django 2.2.6 on 2020-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_pdsversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdsversion',
            name='areaSum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='总面积'),
        ),
        migrations.AlterField(
            model_name='pdsversion',
            name='bpSum',
            field=models.SmallIntegerField(default=0, verbose_name='基本板件数'),
        ),
        migrations.AlterField(
            model_name='pdsversion',
            name='bspSum',
            field=models.SmallIntegerField(default=0, verbose_name='波胶板件数'),
        ),
        migrations.AlterField(
            model_name='pdsversion',
            name='ipdSum',
            field=models.SmallIntegerField(default=0, verbose_name='门中门件数'),
        ),
        migrations.AlterField(
            model_name='pdsversion',
            name='lcpSum',
            field=models.SmallIntegerField(default=0, verbose_name='伸缩板件数'),
        ),
        migrations.AlterField(
            model_name='pdsversion',
            name='lengthSum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='总长度'),
        ),
        migrations.AlterField(
            model_name='pdsversion',
            name='panelSum',
            field=models.SmallIntegerField(default=0, verbose_name='总件数'),
        ),
        migrations.AlterField(
            model_name='pdsversion',
            name='setsSum',
            field=models.SmallIntegerField(default=0, verbose_name='总组数'),
        ),
    ]
