# Generated by Django 2.2.6 on 2020-01-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200116_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='lastversion',
            field=models.SmallIntegerField(default=0, verbose_name='最后版本'),
        ),
    ]
