# Generated by Django 2.2.6 on 2020-03-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200121_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='is_public',
        ),
    ]
