# Generated by Django 2.2.6 on 2020-01-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panels',
            name='panel_type',
        ),
    ]
