# Generated by Django 2.2.6 on 2020-01-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_pdsversion'),
        ('PDS', '0002_remove_panels_panel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelsets',
            name='pdsversion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.pdsVersion', verbose_name='开工纸版本'),
        ),
    ]
