# Generated by Django 2.2.6 on 2019-11-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0002_auto_20191129_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsets',
            name='face_structure',
            field=models.SmallIntegerField(choices=[(0, '无钢结构'), (1, '固面带收边'), (2, '易面带收边'), (3, '固面不带收边')], default=0, verbose_name='屏风结构'),
        ),
    ]
