# Generated by Django 2.2.6 on 2019-10-21 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0010_remove_panelmodels_face_structure'),
        ('PDS', '0002_auto_20191017_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='panles',
            name='panel_pic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='standard.PicsModels', verbose_name='屏风图元'),
        ),
    ]
