# Generated by Django 2.2.6 on 2019-11-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0003_panles_panel_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelsets',
            name='splicer',
            field=models.CharField(default='', max_length=128, verbose_name='横驳条分布'),
        ),
    ]
