# Generated by Django 2.2.6 on 2020-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0003_panelsets_pdsversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsets',
            name='decoration_text',
            field=models.CharField(max_length=256, null=True, verbose_name='装饰面文字说明'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='doorheight',
            field=models.CharField(max_length=64, null=True, verbose_name='门中门门高'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='face_structure',
            field=models.SmallIntegerField(choices=[(0, 'Skinned With Vertical Trim(固面带收边)'), (1, 'Loose With Vertical Trim(易面带收边)'), (2, 'Skinned Trimness(固面不带收边)')], null=True, verbose_name='屏风结构'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='location',
            field=models.CharField(max_length=64, null=True, verbose_name='区域名称'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='lockeyoption_a',
            field=models.SmallIntegerField(choices=[(0, 'None(无)'), (1, 'Key(锁匙)'), (2, 'Knob(旋钮)')], default=None, null=True, verbose_name='A面锁类型'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='lockeyoption_b',
            field=models.SmallIntegerField(choices=[(0, 'None(无)'), (1, 'Key(锁匙)'), (2, 'Knob(旋钮)')], default=None, null=True, verbose_name='B面锁类型'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='note',
            field=models.CharField(max_length=1024, null=True, verbose_name='备注信息'),
        ),
    ]
