# Generated by Django 2.2.6 on 2020-01-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0004_auto_20200116_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsets',
            name='pdsversion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.PdsVersion', verbose_name='开工纸版本'),
        ),
    ]
