# Generated by Django 2.2.6 on 2019-11-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0010_remove_panelmodels_face_structure'),
        ('PDS', '0004_panelsets_splicer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panles',
            new_name='Panels',
        ),
    ]
