# Generated by Django 2.2.6 on 2019-12-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0004_auto_20191206_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsets',
            name='face_structure',
            field=models.SmallIntegerField(choices=[(0, 'None(无钢结构)'), (1, 'Skinned With Vertical Trim(固面带收边)'), (2, 'Loose With Vertical Trim(易面带收边)'), (3, 'Skinned Trimness(固面不带收边)')], default=0, verbose_name='屏风结构'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='sound_test',
            field=models.SmallIntegerField(choices=[(0, 'No(不需要)'), (1, 'Yes(需要)')], verbose_name='隔音测试'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='splicer',
            field=models.CharField(default='无横驳条', max_length=128, verbose_name='横驳条分布'),
        ),
        migrations.AlterField(
            model_name='panelsets',
            name='wheel',
            field=models.SmallIntegerField(choices=[(0, '26#'), (1, '36#'), (2, '57#'), (3, '11#'), (4, '38#'), (5, '40#'), (6, '42#'), (7, '11T#')], verbose_name='轮子'),
        ),
    ]
