# Generated by Django 2.2.6 on 2019-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0005_auto_20191210_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelsets',
            name='decoration_text',
            field=models.CharField(blank=True, max_length=256, verbose_name='装饰面文字说明'),
        ),
        migrations.AddField(
            model_name='panelsets',
            name='decoration_thickness',
            field=models.SmallIntegerField(default=0, verbose_name='装饰面厚度'),
        ),
        migrations.AddField(
            model_name='panelsets',
            name='handle_quantity',
            field=models.SmallIntegerField(default=1, verbose_name='摇手柄数量'),
        ),
        migrations.AddField(
            model_name='panelsets',
            name='location',
            field=models.CharField(blank=True, max_length=64, verbose_name='区域名称'),
        ),
        migrations.AddField(
            model_name='panelsets',
            name='note',
            field=models.CharField(blank=True, max_length=1024, verbose_name='备注信息'),
        ),
    ]
