# Generated by Django 2.2.6 on 2019-11-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0005_auto_20191107_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsets',
            name='production_time',
            field=models.DateTimeField(verbose_name='出厂时间'),
        ),
    ]
