# Generated by Django 2.2.6 on 2019-12-12 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0006_auto_20191210_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipdinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('doorheight', models.CharField(max_length=64, verbose_name='门中门门高')),
                ('lockeroption_a', models.SmallIntegerField(choices=[(0, 'None(无)'), (1, 'Key(锁匙)'), (2, 'Knob(旋钮)')], verbose_name='A面锁类型')),
                ('lockeroption_b', models.SmallIntegerField(choices=[(0, 'None(无)'), (1, 'Key(锁匙)'), (2, 'Knob(旋钮)')], verbose_name='B面锁类型')),
                ('panelset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDS.Panelsets', verbose_name='所属屏风组')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
