# Generated by Django 2.2.6 on 2019-12-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0007_ipdinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipdinfo',
            options={'verbose_name': '门中门列表', 'verbose_name_plural': '门中门列表'},
        ),
        migrations.AlterModelTable(
            name='ipdinfo',
            table='df_ipdinfo',
        ),
    ]
