# Generated by Django 2.2.6 on 2019-12-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDS', '0008_auto_20191213_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdinfo',
            old_name='lockeroption_a',
            new_name='lockeyoption_a',
        ),
        migrations.RenameField(
            model_name='ipdinfo',
            old_name='lockeroption_b',
            new_name='lockeyoption_b',
        ),
    ]
